name: "[Disabled] PreRelease Build"

on:
  workflow_dispatch:

jobs:
  build-prerelease:
    if: false
    runs-on: windows-latest
    
    steps:
    - name: Skip
      run: echo "This workflow has been disabled and merged into release-on-publish.yml"
